services:
  mysql_bp:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${URL_CRAWLER_DB_DATABASE}
      MYSQL_USER: ${URL_CRAWLER_DB_USERNAME}
      MYSQL_PASSWORD: ${URL_CRAWLER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${URL_CRAWLER_DB_ROOT_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:3306"
    volumes:
      - mysql_volume_bp:/var/lib/mysql

volumes:
  mysql_volume_bp:
